driver:
verifier:
  name: inspec
  sudo_command: . /etc/profile;
provisioner:
  name: chef_zero
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/chef-repo/encrypted_data_bag_secret
  require_chef_omnibus: = 13.0
platforms:
- name: ubuntu-14.04-docker
  driver:
    name: docker
    use_sudo: false
    image: eaglegenomics/ehive-docker-run_worker:auto-build
  driver_config:
    instance_name: mapseq_runnable
suites:
- name: default
  includes:
  - ubuntu-14.04-docker
  run_list:
  - role[<%= ENV['CHEF_USER_ROLE'] %>]
  - recipe[mapseq_runnable::default]
