---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "12"
  always_update_cookbooks: true
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/chef-repo/encrypted_data_bag_secret

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
#  - name: centos-7

suites:
  - name: default
    run_list:
      - role[<%= ENV['CHEF_USER_ROLE'] %>]
      - recipe[mapseq_runnable::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
